<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Energy Monitoring Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link 
    rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  >
  <style>
    body { background: #f8f9fa; }
    .card { margin-bottom: 20px; }
  </style>
</head>
<body>
  <div class="container py-4">
    <h1 class="mb-4 text-center">Energy Monitoring Dashboard (Blynk)</h1>
    <div class="row">
      <div class="col-md-4">
        <div class="card text-center">
          <div class="card-header">Voltage (V)</div>
          <div class="card-body">
            <h2 id="voltage">--</h2>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card text-center">
          <div class="card-header">Current (A)</div>
          <div class="card-body">
            <h2 id="current">--</h2>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card text-center">
          <div class="card-header">Power (W)</div>
          <div class="card-body">
            <h2 id="power">--</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-4 text-center">
      <button class="btn btn-primary" onclick="fetchData()">Refresh</button>
    </div>
    <p class="mt-3 text-center text-muted">
      Powered by <a href="https://blynk.io/" target="_blank">Blynk</a>
    </p>
  </div>
  <script>
    // Replace with your Blynk Auth Token (string in Blynk app/device)
    const BLYNK_TOKEN = "YOUR_BLYNK_TOKEN_HERE";
    // Replace with your virtual pin numbers as per your hardware/app setup
    const VIRTUAL_PINS = {
      voltage: "V0",
      current: "V1",
      power:   "V2"
    };

    function fetchBlynkValue(pin) {
      return fetch(`https://blynk.cloud/external/api/get?token=${BLYNK_TOKEN}&${pin}`)
        .then(response => response.json())
        .then(data => data[pin]);
    }

    async function fetchData() {
      document.getElementById("voltage").innerText = "...";
      document.getElementById("current").innerText = "...";
      document.getElementById("power").innerText = "...";
      try {
        const [voltage, current, power] = await Promise.all([
          fetchBlynkValue(VIRTUAL_PINS.voltage),
          fetchBlynkValue(VIRTUAL_PINS.current),
          fetchBlynkValue(VIRTUAL_PINS.power)
        ]);
        document.getElementById("voltage").innerText = voltage ? voltage : "--";
        document.getElementById("current").innerText = current ? current : "--";
        document.getElementById("power").innerText   = power ? power : "--";
      } catch (e) {
        document.getElementById("voltage").innerText = "Error";
        document.getElementById("current").innerText = "Error";
        document.getElementById("power").innerText   = "Error";
        alert("Failed to fetch data from Blynk.");
      }
    }

    // Auto fetch on page load
    window.onload = fetchData;
  </script>
</body>
</html>
